version: '3'
services:
  node:
    image: node:8.1.4
    hostname: node
    container_name: node
    expose:
      - "3000"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
  nginx:
    image: nginx:1.13.3
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    ports:
      - "3000:3000"
